### ISSUE TITLE
Create Wireframes for Creator workflow

### ISSUE THREAD

**Issue by lmosele** [EmmonsVentures/projectsuccotash#1]

**Comment by lmosele** [comment]
@EmmonsVentures are we going to have user auth on mvp? if so what sort of data do we think users will input on account creation?

**Comment by EmmonsVentures** [comment]
@lmosele Yeah I think so.  In order to keep it as simple as possible, I imagine we'll just have users input first name, last name, email, and password.  I would also like to give them the option of signing with twitter, facebook, google, etc.

**Comment by lmosele** [comment]
@EmmonsVentures do we want to do SSO for V2 or do you think we can start outright with a twitter/google/fb login?

**Comment by EmmonsVentures** [comment]
@lmosele Mainly due to my freshness to React/ Redux, lets save SSO for V2.  I'm sure it won't be difficult to implement, I just think there may be better things to focus on for v1.  Also, just thinking out loud here, I don't know how this translates to good design/ ux but what do you think about capturing just the email and password for creation and then have just one button users have to go to to sign in/ sign up.  If they are a user, they will be signed in like normal.  If they aren't, an account is created for them.  Does that make for a confusing user experience?  Curious to hear what you think, it was just an idea that I had.

**Comment by lmosele** [comment]
@EmmonsVentures Im with you on the SSO for V2 and  seamless transition from login to register, its kind of the same direciton I'm going in already, except if the user clicks 'register', an extra two fields will pop up that include first/last name and confirm password and he'll proceed with very little friction.

**Comment by lmosele** [comment]
@EmmonsVentures 

[Simple starting flow here](https://xd.adobe.com/view/4d654963-fdc2-4ccd-7277-f38429685d5b/), still need to workout the text editor UI, full dashboard and then the learner experience, but I think a simple starting point would be something like this. You can follow the flow:

Login > Dashboard or
Register > Dashboard > Create Course > Select Type > Article

**Comment by EmmonsVentures** [comment]
This looks great, Lucas!  Really good starting point.  Should have schemas done by tonight and auth by tomorrow.  We can talk come up with the next steps then.
